### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module '../bin-package'

### ISSUE THREAD

**Issue by dsottimano** [huggingface/node-question-answering#29]
Weird error here, 2 different projects and 1 doesn't have this bin-package folder.  Running node v12.18.4 if anyone has any ideas?

(node:93725) UnhandledPromiseRejectionWarning: Error: Cannot find module '../bin-package'
Require stack:
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/bindings/native.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/bindings/decoders.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/implementations/tokenizers/bert-wordpiece.tokenizer.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/implementations/tokenizers/index.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/index.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/question-answering/dist/qa.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/question-answering/dist/index.js
- /Users/admindave/Source/heroku-fetchlet/fetchlet/controllers/delete.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/admindave/Source/heroku-fetchlet/fetchlet/node_modules/tokenizers/bindings/native.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)

**Comment by dsottimano** [comment]
Weird, re-installing the tokenizers package fixed it.

`npm install tokenizers@latest`

**Comment by Hoodgail** [comment]
i tried doing ``npm install tokenizers@latest`` but im still getting the error

**Comment by gitTerebi** [comment]
I deleted the node_modules folder and npm i and fixed error.
Got this error after running build script.
