### ISSUE TITLE
Issue running node-question-answering

### ISSUE THREAD

**Issue by BirgerMoell** [huggingface/node-question-answering#3]
Hi! Thank you so much for all your incredible work with NLP. I love huggingface.

I tried running this and ran into issues installing.

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.3.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'

**Comment by g-r-e-g** [comment]
Similar problem here, Access Denied downloading the tar.gz

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.4.1/index-v0.4.1-node-v67-linux-x64-glibc.tar.gz

**Comment by ThisCakeIsALie** [comment]
I fixed a similar problem by just updating my node version from v10 to v13.8 and letting the installer install the visual studio build tools (I am on windows 10)

**Comment by Pierrci** [comment]
@g-r-e-g @ThisCakeIsALie indeed, we support the following node versions: 10.x, 12.x and 13.x so your error @g-r-e-g is related to that since you seem to be using node 11.x. I updated the requirements in the `package.json` file.

@ThisCakeIsALie I'm glad that you were able to make it work using v13, although it should have worked on v10, was it a Windows-specific bug?

@BirgerMoell your bug seems to be related to the fsevent package, can you try installing using the `npm install question-answering --only=prod` command? And if still not working, try using node v12? I don't understand why it's requiring fsevent v1.2.9 in your case...

**Comment by Pierrci** [comment]
Closing this, feel free to reopen if still relevant!
