### ISSUE TITLE
NPM Install Error!

### ISSUE THREAD

**Issue by MeechaPooch** [huggingface/node-question-answering#35]
Its not installing uggg!!!!

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'question-answering-tf3@3.0.0',
npm WARN EBADENGINE   required: { node: '>=10 < 11 || >=12 <14' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.7.6' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tokenizers@0.7.0',
npm WARN EBADENGINE   required: { node: '>=10 < 11 || >=12 <14' },
npm WARN EBADENGINE   current: { node: 'v15.14.0', npm: '7.7.6' }
npm WARN EBADENGINE }
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
^A[                  ] / reify:@tensorflow/tfjs-core: http fetch GET 200 https://registry.npmjs.org/@tensorflow/tfjs-cords[                  ] - reify:@tensorflow/tfjs-core: http fetch GET 200 https://registry.npmjs.org/@tensorflow/tfjs-cornpm ERR! code 1
npm ERR! path /mnt/c/Users/*/OneDriveSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/tokenizers
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install
npm ERR! 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
npm ERR! node-pre-gyp info using node@15.14.0 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/mnt/c/Users/*/OneDriveSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/tokenizers/bin-package/index.node" (not found)
npm ERR! node-pre-gyp http GET https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp http 403 https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://tokenizers-releases.s3.amazonaws.com/node/0.7.0/index-v0.7.0-node-v88-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! stack     at Request.<anonymous> (/mnt/c/Users/*/OneDriveSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/node-pre-gyp/lib/install.js:142:27)
npm ERR! node-pre-gyp ERR! stack     at Request.emit (node:events:381:22)
npm ERR! node-pre-gyp ERR! stack     at Request.onRequestResponse (/mnt/c/Users/*/OneDriveSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/request/request.js:1176:10)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:369:20)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:512:22)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:369:20)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:313:12)
npm ERR! node-pre-gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:288:9)
npm ERR! node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/mnt/c/Users/*/OneDriveSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /mnt/c/Users/*/OneDrivSchool/Documents/CODING/PERSONAL/MISC/ArticleParserTest/node_modules/tokenizers
npm ERR! node-pre-gyp ERR! node -v v15.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/*/.npm/_logs/2021-05-27T17_22_58_874Z-debug.log

**Comment by paolagabriellas** [comment]
I am having the same issue

**Comment by Sir-Ignis** [comment]
If using Unix (Mac/Linux) make an sh script with the following (otherwise you can just manually install these):
```
npm install @mapbox/node-pre-gyp
npm install question-answering@latest
```
If you look up node-pre-gyp you will find that it is obsolete and it tells you to upgrade to ``@mapbox/node-pre-gyp``. This should solve your issue!

**Comment by Sir-Ignis** [comment]
> I am having the same issue

If using Unix (Mac/Linux) make an sh script with the following (otherwise you can just manually install these):
```
npm install @mapbox/node-pre-gyp
npm install question-answering@latest
```
If you look up node-pre-gyp you will find that it is obsolete and it tells you to upgrade to ``@mapbox/node-pre-gyp``. This should solve your issue!

**Comment by Sir-Ignis** [comment]
> I am having the same issue

If using Unix (Mac/Linux) make an sh script with the following (otherwise you can just manually install these):
```
npm install @mapbox/node-pre-gyp
npm install question-answering@latest
```
If you look up node-pre-gyp you will find that it is obsolete and it tells you to upgrade to ``@mapbox/node-pre-gyp``. This should solve your issue!

**Comment by MeechaPooch** [comment]
For me, installing node 12.18.3 solved this

**Comment by JeffMII** [comment]
This is a problem with these unmaintained one off projects. After a few years, they become incompatible. Honestly, if the requirement stack didn't include an upper limit on version, "required: { node: '>=10 < 11 || >=12 <14' }", it would most likely work with later versions of node since newer versions include deprecated functionality to maintain back compatibility up to a point. Most of the time, only the lower bound limit needs to be required.

**Comment by JeffMII** [comment]
This project seriously needs an update.

**Comment by creatorrr** [comment]
Node versions above 12 are not working. See https://github.com/huggingface/node-question-answering/issues/41#issuecomment-1040020971
