### ISSUE TITLE
How to test this library?

### ISSUE THREAD

**Issue by balavenkatesh3322** [huggingface/node-question-answering#7]
**How can I run this code to test this project?** 

```
import { QAClient } from "question-answering";

const text = `
  Super Bowl 50 was an American football game to determine the champion of the National Football League (NFL) for the 2015 season.
  The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl title. The game was played on February 7, 2016, at Levi's Stadium in the San Francisco Bay Area at Santa Clara, California.
  As this was the 50th Super Bowl, the league emphasized the "golden anniversary" with various gold-themed initiatives, as well as temporarily suspending the tradition of naming each Super Bowl game with Roman numerals (under which the game would have been known as "Super Bowl L"), so that the logo could prominently feature the Arabic numerals 50.
`;

const question = "Who won the Super Bowl?";

const qaClient = await QAClient.fromOptions();
const answer = await qaClient.predict(question, text);

console.log(answer); // { text: 'Denver Broncos', score: 0.3 }
```

**Do you have a sample js file to test this library?**

**Comment by Pierrci** [comment]
Hi @balavenkatesh3322, a "sample js file" as you say wouldn't be enough, since you also need to download the model following the steps described in the readme:

- Make sure you have at least NodeJS 10 installed on your machine
- Create an empty directory
- Inside the created directory:
	- Run `npm install question-answering@latest`
	- Then run `npx question-answering download`
- You can then create a `js` file with the code you provided, and run `node myfile.js`. It should log `{ text: 'Denver Broncos', score: 0.3 }`.

Just pay attention to the first line of the code, if you're using plain vanilla JS (no Typescript or Babel), you should replace `import { QAClient } from "question-answering";` by `const { QAClient } = require("question-answering");` (I just updated the readme accordingly).

**Comment by balavenkatesh3322** [comment]
Hi @Pierrci ,
Thanks for your explanation. 

I got below error while running this command **npm install question-answering@latest** 
I think Tensorflow js backend is not installed in my machine **@tensorflow/tfjs-node@1.7.0**

```
CPU-linux-1.7.0.tar.gz
* Downloading libtensorflow
[==============================] 8266594/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v5/1.7.0/CPU-linux-1.7.0.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@1.7.0 and node@12.16.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
g++: error: project/node_modules/@tensorflow/tfjs-node/deps/include: No such file or directory
make: *** [tfjs_binding.target.mk:114: Release/obj.target/tfjs_binding/binding/tfjs_backend.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node/lib/napi-v5" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=5" "--node_napi_label=napi-v5"
gyp ERR! cwd /home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node --module_name=tfjs_binding --module_path=/home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node/lib/napi-v5 --napi_version=5 --node_abi_napi=napi --napi_build_version=5 --node_napi_label=napi-v5' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/bala/Documents/aibots/pdf project/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.3.0-40-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/bala/Documents/aibots/pdf project/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/bala/Documents/aibots/pdf project/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 


> tokenizers@0.5.0 install /home/bala/Documents/aibots/pdf project/node_modules/tokenizers
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[tokenizers] Success: "/home/bala/Documents/aibots/pdf project/node_modules/tokenizers/bin-package/index.node" is installed via remote
npm WARN saveError ENOENT: no such file or directory, open '/home/bala/Documents/aibots/pdf project/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/bala/Documents/aibots/pdf project/package.json'
npm WARN pdf project No description
npm WARN pdf project No repository field.
npm WARN pdf project No README data
npm WARN pdf project No license field.

+ question-answering@2.0.0
added 75 packages from 98 contributors and audited 691 packages in 17.156s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

**Comment by Pierrci** [comment]
Can you try replacing the line in error (line 3) with the folliwing:
```js
const { QAClient } = require("question-answering");
```

It seems that although you're running vanilla js, you used some typescript code to import `QAClient`.
